package com.example.reto_2_roho_a.ui.ui.theme

import androidx.compose.ui.graphics.Color

// Colors generated by android studio
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Game color

val BlueXColor = Color(0xFF5B9BD5)
val RedOColor = Color(0xFFED6D6D)
val BoardLineColor = Color(0xFFC0C0C0)
val LightPurple = Color(0xFFD6D4EE)
val PrimaryColor = Color.hsl(47F, 1.0F, 0.53F)
val TextColor = Color.hsl(0F, 0F, 0.35F)